platform :ios, '18.1'

target 'FreezerApp' do
  use_frameworks!

  pod 'Adapty', '~> 3.15.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.1'
    end
  end
end
